### ISSUE TITLE
LLVM/Clang 6.0 port

### ISSUE THREAD

**Issue by kasper3** [joyent/pkgsrc-wip#97]
Is there any effort going on to support latest LLVM toolchain?

Few examples:

Fedora: https://src.fedoraproject.org/rpms/clang/blob/master/f/clang.spec
Gentoo: https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-devel/clang/clang-6.0.0-r1.ebuild
Windows: https://github.com/Microsoft/vcpkg/blob/master/ports/llvm/portfile.cmake

If there are blockers in LLVM toolchain for Solaris in general (chatted with @jperkin once on IRC), could those be reported upstream for our visibility: http://reviews.llvm.org/?

Folks are literally waiting for it since 2015: https://github.com/dotnet/coreclr/issues/803#issuecomment-164936893

**Comment by jperkin** [comment]
One of the main changes in our 2018Q1 release was the inclusion of an LLVM/clang 6.0.0rc3 suite.  https://illumos.topicbox.com/groups/discuss/T2309ed4a8c6240ec

**Comment by kasper3** [comment]
This is a great news! Thanks @jperkin.

Is LLDB included? I have found https://github.com/joyent/pkgsrc/tree/trunk/devel/lldb, which appears to be older version.

**Comment by jperkin** [comment]
Not yet, I'd like to look at this if I get time though.

**Comment by kasper3** [comment]
@jperkin, thank you. Should I open an issue in joyent/pkgsrc requesting LLDB package to track this?

Here is a reference script: https://src.fedoraproject.org/rpms/lldb/blob/master/f/lldb.spec. Please note that in release_60 of lldb, we had to add one patch for cmake in Fedora, Debian/Ubuntu, Gentoo (and many other ports), which upstream fixed few days after release_60. Fedora patch looks like this https://src.fedoraproject.org/rpms/lldb/blob/master/f/0001-Partially-revert-CMake-Cleanup-unnecessary-definitio.patch, but upstream patch looks like: https://github.com/llvm-mirror/lldb/commit/8f577000b2fe2f5bf5d08e352a2f15f9421f9c82, which was added in Debian (http://metadata.ftp-master.debian.org/changelogs/main/l/llvm-toolchain-6.0/llvm-toolchain-6.0_6.0-3_changelog - ref: 895051) and Ubuntu (https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-6.0/+bug/1761009).

If you want I can also take a crack at it over the weekend. :)

**Comment by jperkin** [comment]
I've pushed an initial package in https://github.com/joyent/pkgsrc-joyent/commit/9bada8d93ec08e0c4f78bd76c171dbbc52a5705f, you are welcome to start with that (a colleague has expressed interest in this too).

**Comment by kasper3** [comment]
Thanks! I will setup the pkgsrc zone and will try to compile it. :)

**Comment by kasper3** [comment]
@jperkin, could you please walk me through how to get zone that has pkgsrc-joyent's master branch?

```sh
imgadm sources -a <what goes here>
imgadm avail | grep <what goest here>
# so i can get UUID and do

imgadm import <UUID>
```

I am still wrapping my head around basic usage of Solaris :)

**Comment by jperkin** [comment]
https://github.com/joyent/pkgsrc/wiki/pkgdev:setup

You'll want the 18.1.0 pkgbuild image, create a 2018Q1-x86_64 sandbox, and then do a 'git pull' in `/data/pkgsrc/joyent` to get the latest including my initial lldb6 package.

The basics of building and patching are then described in

https://github.com/joyent/pkgsrc/wiki/pkgdev:building
https://github.com/joyent/pkgsrc/wiki/pkgdev:fixing

**Comment by kasper3** [comment]
Thanks! I followed the steps and get to compile step. Some compilation errors popped up even when using c++11 with g++49.
Can we point LLVM and clang to releases.llvm.org 6.0.0, instead of prereleases 6.0.0-rc3?
